[Connection_Details]

	db_host =  'localhost'
	db_name = 'testdatabase'
	db_username = 'root'
	db_password = ''
	default_table = 'testtable'

[autoload]
	
	#; fill the variable 'update' with all the file-abbreviations from 'updatable' that you want to have synced
	#; use the key given in the chapter [repo_files] in includables.ini
	#;update = 'auto,inc,array,cook,html,mail,osd,sms,sql,util,wc'
	update = ['array', 'cook', 'html']
	#; time in minutes that files are NOT updated (to avoid ) 
	cache_time = 15

[smtp_settings]
	host = 'your.smtp.server.com'
	username = 'info@yourdomain.com'
	password = 'yourSMTPpassword'
	from = 'your@adress.com'
	